steps:
- name: 'gcr.io/cloud-builders/mvn:3.5.0-jdk-8'
  args: ['clean', 'install']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/patients-image:$REVISION_ID', '.' ]
images:
- 'gcr.io/$PROJECT_ID/patients-image:v1'
