steps:
        - name: maven:3.5.0-jdk-8
          entrypoint: 'mvn'
          args: ['install']
        - name: 'gcr.io/cloud-builders/mvn'
          args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/patients_image', '.' ]
        images:
        - 'gcr.io/$PROJECT_ID/patients_image'
